name: CI_CD
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@4.1.5
      - name: Autenticaçao no Docker HUB
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build da Imagem Docker
        uses: docker/build-push-action@5.3.0
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: |
            rycpyres/aula-primeira-pipeline:v${{ github.run_number }}
            rycpyres/aula-primeira-pipeline:latest