name: CI/CD Fake
on:
  workflow_dispatch:
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Build de Imagem Docker
        run: echo "Execução do comando de docker build"
      - name: Execução de Teste de software
        run: echo "Execução do comando de teste"
      - name: Publicando a Release
        run: echo "Execução do comando de publicação"
  